import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
  route("robots.txt", "routes/robots[.]txt.tsx"),
  route("select-lang", "routes/legacy-path-redirect.tsx", {
    id: "routes/legacy-select-lang",
  }),
  route("izbor-jezika", "routes/select-lang.tsx"),
  route(":lang?", "routes/home.tsx"),
  route(":lang?/faq", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-faq" }),
  route(":lang?/contact", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-contact" }),
  route(":lang?/blog", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-blog" }),
  route(":lang?/blog/:slug", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-blog-details" }),
  route(":lang?/success", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-success" }),
  route(":lang?/cars", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-cars" }),
  route(":lang?/rental-conditions", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-rental-conditions" }),
  route(":lang?/privacy-policy", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-privacy-policy" }),
  route(":lang?/long-term-rental", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-long-term-rental" }),
  route(":lang?/reservation", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-reservation" }),
  route(":lang?/reservation/vehicle", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-reservation-vehicle" }),
  route(":lang?/reservation/extras", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-reservation-extras" }),
  route(":lang?/reservation/review", "routes/legacy-path-redirect.tsx", { id: "routes/legacy-reservation-review" }),
  route(":lang?/cesta-pitanja", "routes/faq-page.tsx"),
  route(":lang?/kontakt", "routes/contact-page.tsx"),
  route(":lang?/vesti", "routes/blog-page.tsx"),
  route(":lang?/vesti/:slug", "routes/blog-details.tsx"),
  route(":lang?/uspesno", "routes/success.tsx"),
  route(":lang?/wspay/redirect", "routes/wspay-redirect.tsx"),
  route(":lang?/wspay/success", "routes/wspay-success.tsx"),
  route(":lang?/wspay/error", "routes/wspay-error.tsx"),
  route(":lang?/wspay/cancel", "routes/wspay-cancel.tsx"),
  route(":lang?/vozila", "routes/cars-page.tsx"),
  route(":lang?/uslovi-iznajmljivanja", "routes/rental-conditions-page.tsx"),
  route(":lang?/politika-privatnosti", "routes/privacy-policy-page.tsx"),
  route(":lang?/dugorocni-najam", "routes/long-term-rental.tsx"),
  route(":lang?/rezervacija", "routes/reservation-page.tsx", [
    index("routes/reservation/index.tsx"),
    route("vozilo", "routes/reservation/vehicle.tsx"),
    route("dodaci", "routes/reservation/extras.tsx"),
    route("pregled", "routes/reservation/review.tsx"),
  ]),
] satisfies RouteConfig;
